### ISSUE TITLE
Labels changed color to `colors.bug` (red) without change in definition

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-labelsync#34]
Hmm, seems something went wrong with the removal of all the labels:

https://github.com/prisma/prisma2/labels
https://github.com/prisma/lift/labels
https://github.com/prisma/photonjs/labels
https://github.com/prisma/studio/labels

`kind/bug` used to be blue, now it is red:

![image](https://user-images.githubusercontent.com/183673/62899011-1eea8080-bd57-11e9-85ef-bc90a9ac986d.png)

https://circleci.com/gh/prisma/prisma-label-sync/151 doesn't really show if this was caused by the last PR, but it obviously make sense because that is the only thing that happened in the meantime.

What am I missing here?
Does this have to do something with #31?

**Comment by janpio** [comment]
Interesting to note that `kind/bug` is the only "sibling" label we are using here, so maybe this is influenced by that as well?

(Ping @maticzav as it is blocking #30 for us)

**Comment by janpio** [comment]
Uhhh, the color seems to be back to the correct blue now:

![image](https://user-images.githubusercontent.com/183673/63092535-56794880-bf62-11e9-91a6-272c8ebaa784.png)

@matthewmueller did an unrelated thing, maybe this had as a sideffect to fix this!?

**Comment by janpio** [comment]
Ok, this is the run of what @matthewmueller did: https://circleci.com/gh/prisma/prisma-label-sync/155

![image](https://user-images.githubusercontent.com/183673/63092678-c8519200-bf62-11e9-9c92-172c9e0fa38f.png)

But his changes didn't affect anything besides `prisma/specs` at all:
https://github.com/prisma/prisma-label-sync/commit/27ed0bbc6f83327b788a30d44fcfc293fdabface

Something fishy is going on here.

**Comment by janpio** [comment]
(I merged another thing (new label `kind/regression`) and nothing bad happened.)

**Comment by maticzav** [comment]
@janpio you should take into consideration that when you merge PR, `label-sync` compares the current state and updates it according to configuration. `label-sync` does not work as a service yet, that's why it's possible to see changes in new repositories which don't reflect changes in the code.

Does this clarify the issue?

**Comment by janpio** [comment]
No, not really. It changed the `kind/bug` label to a color that was not set for that label anywhere.

**Comment by janpio** [comment]
Ok, I think we have this problem again, not in `prisma/specs` and it changed all `area/*` label from yellow to red:

https://github.com/prisma/specs/labels

![image](https://user-images.githubusercontent.com/183673/63579694-7f699100-c593-11e9-84a9-3453c553d715.png)

Those used to and should be yellow: https://www.colorhexa.com/ffd700

Defined here:

https://github.com/prisma/prisma-label-sync/blob/e02b85d4febeb771d692117ef937b1979af3292f/src/labels/repositories/specs.ts#L14-L25

https://github.com/prisma/prisma-label-sync/blob/e02b85d4febeb771d692117ef937b1979af3292f/src/labels/common/prisma2.ts#L1-L11

How can we investigate this?

**Comment by maticzav** [comment]
@janpio I am not sure I understand the problem. If no person from Prisma authorised the overwrite, `label-sync` couldn't have changed the colour. As I said, `label-sync` is not yet a service but a CLI tool.

Did anyone verify the change to red colour?

**Comment by janpio** [comment]
No I did not change the defined color of the label - which is exactly why I created this issue here. 

Somehow `label-sync` changes the color of labels, without the definition being changed. I also couldn't find any output that would have told me about the color change (see the CI runs from all commits in this repo), so I am kind of stumped.

There were unrelated changes (labels added, colors of other labels changed), but those did definitely not include changing the label color to red.

**Comment by maticzav** [comment]
Just to clarify, supposed colour changes are not indicated in the report but only in the Github labels section?

**Comment by janpio** [comment]
No.

We change unrelated things (Add labels, remove labels), nothing unexpected shows up in the dry run, we execute it and the actual changes happen. Some time later we notice unrelated color changes and are not sure where those come from. We did not manually change the color, so our conclusion is that usage of this repo here somehow messed with the (unrelated) colors.

**Comment by maticzav** [comment]
I understand the logical conclusion but, I mean, if the tool doesn't run it can't commit changes. It is not a service, as mentioned, but a CLI tool. I understand your frustration, I would be frustrated as well, but I honestly don't know what to do. There's no way to replicate the behaviour, the tool is a CLI, not a service, it's covered 100% by tests, and before you, there were no issues with it.

There's literally a break that prevents code from being written https://github.com/maticzav/label-sync/blob/dcb97d73a0ca4d3483cd07ed48bbea5bd76cc5b1/packages/label-sync-core/src/handlers/labels/sync.ts#L49, and the result of sync directly correlates with the output.

Please, give me something that I can use to reproduce the bug, be it logs that indicate the change or anything else. There's not a single constant in `label-sync` that would change labels to `red`.

**Comment by janpio** [comment]
> Please, give me something that I can use to reproduce the bug, be it logs that indicate the change or anything else. There's not a single constant in `label-sync` that would change labels to `red`.

See my question in a previous comment:

> How can we investigate this @maticzav?

I have no idea how I could figure out where things are going wrong:

- I think I didn't mess up anything in the PRs I created and merged
- I checked the dry run output before approving - nothing indicated that label colors would be changed
- I also checked the live run output after noticing the problem - nothing indicates that label colors were changed
- No one changed the colors manually

---

What would my way out be here? 
Should I just manually change the colors back to what they _should_ be? 
Or should I create an unrelated no-op change (e.g. adding a `.` to a description of one of the labels) to see if label-sync then changes the color back to what they should be?
Or should I not do anything until we figure out what is/was wrong?

---

What should I look for next time I create an unrelated change?

**Comment by janpio** [comment]
Unfortunately had to move forward with new merges. 

This a) fixed the label color of the `area/*` labels in `specs` and b) actually failed doing all its tasks, see https://github.com/prisma/prisma-label-sync/issues/51

So the only thing I can do for now is keep observing for potential unwanted label color changes and report here again if I see something.
